name: Test suite

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Commented sections to be uncommented once CI is active
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        requires: ["requirements.txt"]
        # Can't use 2.7 with fsl from conda
        # python-version: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        # Can't drop requirements.txt without build isolation
        # requires: ["", "requirements.txt"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/,conda-forge
          environment-file: .github/test-env.yml
      - name: Update pip and pytest
        run: python -m pip install --upgrade pip pytest pytest-cov
      - name: Install requires
        run: |
          python -m pip install -r ${{ matrix.requires }}
        if: ${{ matrix.requires }}
      - name: Install gradunwarp
        run: |
          python -m pip install .
      - name: Test
        run: pytest --cov gradunwarp
